### ISSUE TITLE
License

### ISSUE THREAD

**Issue by huseyinkozan** [OATS-Group/isoblue2#1]
Hello,

Is this a closed source repo ?

https://github.com/OATS-Group/meta-isoblue/blob/master/recipes-core/isoblue-software/isoblue-software_1.1.bb#L3

**Comment by wang701** [comment]
Fixed in [f317126](https://github.com/ISOBlue/meta-isoblue/commit/f317126ef8db34e77428bd0373f4cec15180f200).
